fix(deps): update all non-major dependencies (#205)
This PR contains the following updates:

| Package | Change | Age | Confidence |
|---|---|---|---|
| [@ast-grep/napi](https://ast-grep.github.io)
([source](https://redirect.github.com/ast-grep/ast-grep)) | [`^0.38.5`
->
`^0.39.1`](https://renovatebot.com/diffs/npm/@ast-grep%2fnapi/0.38.6/0.39.1)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@ast-grep%2fnapi/0.39.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@ast-grep%2fnapi/0.38.6/0.39.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[@types/node](https://redirect.github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node)
([source](https://redirect.github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/node))
| [`24.0.3` ->
`24.1.0`](https://renovatebot.com/diffs/npm/@types%2fnode/24.0.3/24.1.0)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@types%2fnode/24.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@types%2fnode/24.0.3/24.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [eslint](https://eslint.org)
([source](https://redirect.github.com/eslint/eslint)) | [`9.29.0` ->
`9.31.0`](https://renovatebot.com/diffs/npm/eslint/9.29.0/9.31.0) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/eslint/9.31.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/eslint/9.29.0/9.31.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [knip](https://knip.dev)
([source](https://redirect.github.com/webpro-nl/knip/tree/HEAD/packages/knip))
| [`5.61.2` ->
`5.62.0`](https://renovatebot.com/diffs/npm/knip/5.61.2/5.62.0) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/knip/5.62.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/knip/5.61.2/5.62.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [lefthook](https://redirect.github.com/evilmartians/lefthook) |
[`1.11.14` ->
`1.12.2`](https://renovatebot.com/diffs/npm/lefthook/1.11.14/1.12.2) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/lefthook/1.12.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/lefthook/1.11.14/1.12.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [prettier](https://prettier.io)
([source](https://redirect.github.com/prettier/prettier)) | [`3.5.3` ->
`3.6.2`](https://renovatebot.com/diffs/npm/prettier/3.5.3/3.6.2) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/prettier/3.6.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/prettier/3.5.3/3.6.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>ast-grep/ast-grep (@&#8203;ast-grep/napi)</summary>

###
[`v0.39.1`](https://redirect.github.com/ast-grep/ast-grep/blob/HEAD/CHANGELOG.md#0391)

[Compare
Source](https://redirect.github.com/ast-grep/ast-grep/compare/0.38.7...0.39.1)

> 20 July 2025

- fix: update package
[`8c2327b`](https://redirect.github.com/ast-grep/ast-grep/commit/8c2327b247dbe3b218a7a888480a7cf0ad765fb4)
- fix: fix build
[`d59c219`](https://redirect.github.com/ast-grep/ast-grep/commit/d59c219299af827da11a52f9e7f8ffbbb3ebaeb8)
- fix: remove json format
[`90369a4`](https://redirect.github.com/ast-grep/ast-grep/commit/90369a4cf698e8d3cbdc9c872f852c277588521b)

###
[`v0.38.7`](https://redirect.github.com/ast-grep/ast-grep/releases/tag/0.38.7)

[Compare
Source](https://redirect.github.com/ast-grep/ast-grep/compare/0.38.6...0.38.7)

- refactor: remove biome configuration and update linting tool to oxlint
[`ed3e5b1`](https://redirect.github.com/ast-grep/ast-grep/commit/ed3e5b1197b1ebec1533021fd446366eac0d2408)
- chore(deps): update dependency
[@&#8203;ast-grep/napi](https://redirect.github.com/ast-grep/napi) to
v0.38.6
[`9e5f1e0`](https://redirect.github.com/ast-grep/ast-grep/commit/9e5f1e070aed4557f998db0c4cab97f4aead9fbe)
- Revert "fix(deps): update rust crate tower-lsp-server to 0.22.0"
[`7d8e872`](https://redirect.github.com/ast-grep/ast-grep/commit/7d8e872b5b4aea3bd5d1c3f7311d375378e8181a)

</details>

<details>
<summary>eslint/eslint (eslint)</summary>

###
[`v9.31.0`](https://redirect.github.com/eslint/eslint/compare/v9.30.1...14053edc64bd378ab920575f2488fbfcbb5a4ea0)

[Compare
Source](https://redirect.github.com/eslint/eslint/compare/v9.30.1...v9.31.0)

###
[`v9.30.1`](https://redirect.github.com/eslint/eslint/compare/v9.30.0...6769b5fa11ecfb2c2cf78472d3d90564a1e01d3c)

[Compare
Source](https://redirect.github.com/eslint/eslint/compare/v9.30.0...v9.30.1)

###
[`v9.30.0`](https://redirect.github.com/eslint/eslint/compare/v9.29.0...ad1d63951773acc7828bcc1eafbb731567447298)

[Compare
Source](https://redirect.github.com/eslint/eslint/compare/v9.29.0...v9.30.0)

</details>

<details>
<summary>webpro-nl/knip (knip)</summary>

###
[`v5.62.0`](https://redirect.github.com/webpro-nl/knip/releases/tag/5.62.0)

[Compare
Source](https://redirect.github.com/webpro-nl/knip/compare/5.61.3...5.62.0)

- Support `.ts` extension in `toLilconfig`utility for default TS configs
([#&#8203;1157](https://redirect.github.com/webpro-nl/knip/issues/1157))
([`cbfb9c3`](https://redirect.github.com/webpro-nl/knip/commit/cbfb9c3b1c6fd4f77b5e5f0987e0f027ee609feb))
- thanks [@&#8203;what1s1ove](https://redirect.github.com/what1s1ove)!
- Update reporters to have the correct name for the default reporter
([#&#8203;1165](https://redirect.github.com/webpro-nl/knip/issues/1165))
([`bf81146`](https://redirect.github.com/webpro-nl/knip/commit/bf811460b57a5c6ce1773dae3956edf62f50ce81))
- thanks
[@&#8203;gavinhenderson](https://redirect.github.com/gavinhenderson)!
- Add `audit` as a valid command for bun
([#&#8203;1168](https://redirect.github.com/webpro-nl/knip/issues/1168))
([`014cbaa`](https://redirect.github.com/webpro-nl/knip/commit/014cbaac78e1ccd09830b7e5bbe8389035f82880))
- thanks [@&#8203;carlosedp](https://redirect.github.com/carlosedp)!
- Fix Angular plugin to allow for
[@&#8203;angular/build](https://redirect.github.com/angular/build)
([#&#8203;1175](https://redirect.github.com/webpro-nl/knip/issues/1175))
([`0754130`](https://redirect.github.com/webpro-nl/knip/commit/0754130ed26cb4cba6a15bcc708836e1218a4aae))
- thanks [@&#8203;davidlj95](https://redirect.github.com/davidlj95)!
- Correctly detect used/unused namespace exports that begin with double
underscores
([#&#8203;1180](https://redirect.github.com/webpro-nl/knip/issues/1180))
([`259a2f6`](https://redirect.github.com/webpro-nl/knip/commit/259a2f693be762cb3459a7756ee8fad20075c5e3))
- thanks [@&#8203;akallem](https://redirect.github.com/akallem)!
- Rename tsconfig-loader.ts → load-tsconfig.ts
([`61280b0`](https://redirect.github.com/webpro-nl/knip/commit/61280b0ef37161b889959062dbbd750783c8e7a2))
- Support absolute path for config argument
([`b606681`](https://redirect.github.com/webpro-nl/knip/commit/b6066816cc1950515af8c76f956e06d23b4e6784))
- Fix formatting
([`ebc9202`](https://redirect.github.com/webpro-nl/knip/commit/ebc9202f7ae303edafd01921d26b11c871f90ac7))
- Add bun.lock support in
[@&#8203;knip/create-config](https://redirect.github.com/knip/create-config)
([#&#8203;1182](https://redirect.github.com/webpro-nl/knip/issues/1182))
([`da80ab3`](https://redirect.github.com/webpro-nl/knip/commit/da80ab33cccf611143e44d81eb78680e960cce33))
- thanks [@&#8203;ShooTeX](https://redirect.github.com/ShooTeX)!
- Support new biome config extends definition
([#&#8203;1177](https://redirect.github.com/webpro-nl/knip/issues/1177))
([`07439ef`](https://redirect.github.com/webpro-nl/knip/commit/07439ef3af85dab40df7596f2c0ae5d392e16b3f))
- thanks [@&#8203;Thomascogez](https://redirect.github.com/Thomascogez)!
- Support Vitest projects configuration for dynamic project discovery
([#&#8203;1171](https://redirect.github.com/webpro-nl/knip/issues/1171))
([`cd0ed32`](https://redirect.github.com/webpro-nl/knip/commit/cd0ed32c66c310db835210fd50f579cb54641d23))
- thanks [@&#8203;yyxi](https://redirect.github.com/yyxi)!
- Fix up ESLint flat config resolution (replace
[#&#8203;1173](https://redirect.github.com/webpro-nl/knip/issues/1173))
([`021ecff`](https://redirect.github.com/webpro-nl/knip/commit/021ecfff467ce6fa8d23fe3e046364807006cbcd))
- Reuse existing entry/production patterns in astro plugin
([`e65f709`](https://redirect.github.com/webpro-nl/knip/commit/e65f7099facb55d28c305051c04f2fabfba58d07))
- Edit docs
([`10f8a4f`](https://redirect.github.com/webpro-nl/knip/commit/10f8a4f3ec850624d91c87d0187a9326142af12d))

###
[`v5.61.3`](https://redirect.github.com/webpro-nl/knip/releases/tag/5.61.3)

[Compare
Source](https://redirect.github.com/webpro-nl/knip/compare/5.61.2...5.61.3)

- docs: add config docs for compilers and treatConfigHintsAsErrors, move
Plugins and Workspace to group level
([#&#8203;1152](https://redirect.github.com/webpro-nl/knip/issues/1152))
([`93375c8`](https://redirect.github.com/webpro-nl/knip/commit/93375c826702645197279652d7f2b5184d9e3275))
- thanks
[@&#8203;cylewaitforit](https://redirect.github.com/cylewaitforit)!
- Release 1.0.6
([`46ca323`](https://redirect.github.com/webpro-nl/knip/commit/46ca32343d39807fc7a89d6e25193ed294dc3c0d))
- Remove unnecessary await in test
([`6a7964d`](https://redirect.github.com/webpro-nl/knip/commit/6a7964d37ebb60fbd34147e8d948f9a2ef0bf82f))
- PackageJsonPeeker → PackagePeeker
([`f0087f8`](https://redirect.github.com/webpro-nl/knip/commit/f0087f883b8797f023a7418aeef86aacc9d9f3a3))
- Minor refactor/rename
([`457e8ff`](https://redirect.github.com/webpro-nl/knip/commit/457e8ff4e4e2a41401b63adb0d3c0dee821ace36))
- Fix absolute path in karma plugin
([`c40751b`](https://redirect.github.com/webpro-nl/knip/commit/c40751b37292d014e0d774baef0e85ddeb0ed3a4))
- Update docs re. dev
([`cc55504`](https://redirect.github.com/webpro-nl/knip/commit/cc555048f503815c792e276d39cbf2ad65229b26))
- Refactor post-processing of irregular imports/resolveds
([#&#8203;1156](https://redirect.github.com/webpro-nl/knip/issues/1156))
([`aaa1bd0`](https://redirect.github.com/webpro-nl/knip/commit/aaa1bd0121464012a050bce7cf8250724485b138))
- Add config file to cache
([#&#8203;1156](https://redirect.github.com/webpro-nl/knip/issues/1156))
([`0b49c69`](https://redirect.github.com/webpro-nl/knip/commit/0b49c69c0eec55671cb94efb021a2e3a0bee4db1))
- Don't overwrite cached config file inputs in same run (resolves
[#&#8203;1156](https://redirect.github.com/webpro-nl/knip/issues/1156))
([`efe2d5d`](https://redirect.github.com/webpro-nl/knip/commit/efe2d5d67c9374357a8137334dca90ac44fa2ef7))
- Consolidate file node post-processing in one place
([`843b69b`](https://redirect.github.com/webpro-nl/knip/commit/843b69b7d387bf8683037eca03a12618df9fe28e))
- Add "Debug Node test" launch configs
([`5a76a6c`](https://redirect.github.com/webpro-nl/knip/commit/5a76a6c5d77ea156c810e6bab89aaac0c3f9e5f1))

</details>

<details>
<summary>evilmartians/lefthook (lefthook)</summary>

###
[`v1.12.2`](https://redirect.github.com/evilmartians/lefthook/blob/HEAD/CHANGELOG.md#1122-2025-07-11)

[Compare
Source](https://redirect.github.com/evilmartians/lefthook/compare/v1.12.1...v1.12.2)

- feat: add implicit template lefthook\_job\_name
([#&#8203;1074](https://redirect.github.com/evilmartians/lefthook/pull/1074))
- docs: restructure documentation
([#&#8203;1075](https://redirect.github.com/evilmartians/lefthook/pull/1075))
by [@&#8203;mrexox](https://redirect.github.com/mrexox)
- feat: allow overriding config path using LEFTHOOK\_CONFIG env
([#&#8203;1072](https://redirect.github.com/evilmartians/lefthook/pull/1072))
by [@&#8203;TECHNOFAB11](https://redirect.github.com/TECHNOFAB11)

###
[`v1.12.1`](https://redirect.github.com/evilmartians/lefthook/blob/HEAD/CHANGELOG.md#1121-2025-07-09)

[Compare
Source](https://redirect.github.com/evilmartians/lefthook/compare/v1.12.0...v1.12.1)

- feat: add check-install command
([#&#8203;1064](https://redirect.github.com/evilmartians/lefthook/pull/1064))
by [@&#8203;mrexox](https://redirect.github.com/mrexox)
- chore: only check if local configs exist by
[@&#8203;mrexox](https://redirect.github.com/mrexox)
- feat: allow using local config only
([#&#8203;1071](https://redirect.github.com/evilmartians/lefthook/pull/1071))
by [@&#8203;sj26](https://redirect.github.com/sj26)

###
[`v1.12.0`](https://redirect.github.com/evilmartians/lefthook/blob/HEAD/CHANGELOG.md#1120-2025-07-08)

[Compare
Source](https://redirect.github.com/evilmartians/lefthook/compare/v1.11.16...v1.12.0)

- feat: allow installing only specific hooks
([#&#8203;1069](https://redirect.github.com/evilmartians/lefthook/pull/1069))
- refactor: \[**breaking**] restructure files and folders, remove
deprecated options
([#&#8203;1067](https://redirect.github.com/evilmartians/lefthook/pull/1067))

###
[`v1.11.16`](https://redirect.github.com/evilmartians/lefthook/blob/HEAD/CHANGELOG.md#11116-2025-07-03)

[Compare
Source](https://redirect.github.com/evilmartians/lefthook/compare/v1.11.15...v1.11.16)

- fix: race condition on repo state
([#&#8203;1066](https://redirect.github.com/evilmartians/lefthook/pull/1066))

###
[`v1.11.15`](https://redirect.github.com/evilmartians/lefthook/blob/HEAD/CHANGELOG.md#11115-2025-07-03)

[Compare
Source](https://redirect.github.com/evilmartians/lefthook/compare/v1.11.14...v1.11.15)

- feat: add exclude arg
([#&#8203;1063](https://redirect.github.com/evilmartians/lefthook/pull/1063))
- feat: inherit group envs
([#&#8203;1061](https://redirect.github.com/evilmartians/lefthook/pull/1061))
- fix: apply implicit staged files filter to all files when all files
arg given
([#&#8203;1062](https://redirect.github.com/evilmartians/lefthook/pull/1062))
- deps: bump github.com/kaptinlin/jsonschema to 0.4.5
- deps: bump github.com/knadh/koanf/parsers/yaml to 1.1.0
- deps: bump github.com/knadh/koanf/v2 to 2.2.1
([#&#8203;1043](https://redirect.github.com/evilmartians/lefthook/pull/1043))
- fix: friendlier updater error message
- fix: bump goreleaser

</details>

<details>
<summary>prettier/prettier (prettier)</summary>

###
[`v3.6.2`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#362)

[Compare
Source](https://redirect.github.com/prettier/prettier/compare/3.6.1...3.6.2)


[diff](https://redirect.github.com/prettier/prettier/compare/3.6.1...3.6.2)

##### Markdown: Add missing blank line around code block
([#&#8203;17675](https://redirect.github.com/prettier/prettier/pull/17675)
by [@&#8203;fisker](https://redirect.github.com/fisker))

<!-- prettier-ignore -->

````md
<!-- Input -->
1. Some text, and code block below, with newline after code block

   ```yaml
   ---
   foo: bar
   ```

   1. Another
   2. List

<!-- Prettier 3.6.1 -->
1. Some text, and code block below, with newline after code block

   ```yaml
   ---
   foo: bar
   ```
   1. Another
   2. List

<!-- Prettier 3.6.2 -->
1. Some text, and code block below, with newline after code block

   ```yaml
   ---
   foo: bar
   ```

   1. Another
   2. List
````

###
[`v3.6.1`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#361)

[Compare
Source](https://redirect.github.com/prettier/prettier/compare/3.6.0...3.6.1)


[diff](https://redirect.github.com/prettier/prettier/compare/3.6.0...3.6.1)

##### TypeScript: Allow const without initializer
([#&#8203;17650](https://redirect.github.com/prettier/prettier/pull/17650),
[#&#8203;17654](https://redirect.github.com/prettier/prettier/pull/17654)
by [@&#8203;fisker](https://redirect.github.com/fisker))

<!-- prettier-ignore -->

```jsx
// Input
export const version: string;

// Prettier 3.6.0 (--parser=babel-ts)
SyntaxError: Unexpected token (1:21)
> 1 | export const version: string;
    |                     ^

// Prettier 3.6.0 (--parser=oxc-ts)
SyntaxError: Missing initializer in const declaration (1:14)
> 1 | export const version: string;
    |              ^^^^^^^^^^^^^^^

// Prettier 3.6.1
export const version: string;
```

##### Miscellaneous: Avoid closing files multiple times
([#&#8203;17665](https://redirect.github.com/prettier/prettier/pull/17665)
by [@&#8203;43081j](https://redirect.github.com/43081j))

When reading a file to infer the interpreter from a shebang, we use the
`n-readlines` library to read the first line in order to get the
shebang.

This library closes files when it reaches EOF, and we later try close
the same
files again. We now close files only if `n-readlines` did not already
close
them.

###
[`v3.6.0`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#360)

[Compare
Source](https://redirect.github.com/prettier/prettier/compare/3.5.3...3.6.0)


[diff](https://redirect.github.com/prettier/prettier/compare/3.5.3...3.6.0)

🔗 [Release Notes](https://prettier.io/blog/2025/06/23/3.6.0)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - Between 12:00 AM and 03:59 AM, only on
Monday ( * 0-3 * * 1 ) (UTC), Automerge - At any time (no schedule
defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get
[config
help](https://redirect.github.com/renovatebot/renovate/discussions) if
that's undesired.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0MS4yMy4yIiwidXBkYXRlZEluVmVyIjoiNDEuNDMuNSIsInRhcmdldEJyYW5jaCI6InRydW5rIiwibGFiZWxzIjpbImRlcGVuZGVuY2llcyJdfQ==-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>